"""Generate a LiteLLM `config.yaml` from a user selection (AGENTS.md §5.3, §6).

The generated YAML never contains secrets: the provider key and master key are
referenced as `os.environ/<NAME>` and supplied to the LiteLLM process via env
vars at start time.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from .constants import (
    MAIN_ALIAS,
    MASTER_KEY_ENV,
    PROVIDER_BASE_ENV,
    PROVIDER_KEY_ENV,
    SMALL_ALIAS,
)
from .providers import Provider, get_provider, needs_responses_api


@dataclass
class Selection:
    """A fully-resolved bridge selection ready to be turned into config + env."""

    provider_id: str
    main_model: str
    small_model: Optional[str] = None  # defaults to main_model when None
    api_base: Optional[str] = None
    catch_all: bool = True  # add a "*" alias mapping unknown tiers to main

    @property
    def provider(self) -> Provider:
        return get_provider(self.provider_id)

    @property
    def effective_small_model(self) -> str:
        return self.small_model or self.main_model

    @property
    def main_target(self) -> str:
        return self.provider.full_model(self.main_model)

    @property
    def small_target(self) -> str:
        return self.provider.full_model(self.effective_small_model)


def _yaml_quote(value: str) -> str:
    """Double-quote a scalar for YAML, escaping backslashes and quotes.

    Safe for model strings and the `os.environ/...` references alike (quoting
    does not change the resolved string for LiteLLM).
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _alias_repr(alias: str) -> str:
    """Render a model_name alias, quoting it when YAML needs it.

    Plain identifiers (claudia-main) stay bare; the catch-all "*" MUST be quoted
    because a bare `*` is a YAML alias indicator and fails to parse.
    """
    if alias.replace("-", "").replace("_", "").isalnum():
        return alias
    return _yaml_quote(alias)


def _model_entry(
    alias: str,
    target: str,
    provider: Provider,
    api_base: Optional[str],
    responses_mode: bool = False,
) -> list[str]:
    """Render one `model_list` entry as a list of YAML lines.

    When `responses_mode` is set, emit `model_info: { mode: responses }` so
    LiteLLM routes this model through the Responses API (/v1/responses) instead
    of /v1/chat/completions — required for Copilot gpt-5.4+/codex with tools +
    reasoning_effort.
    """
    lines = [f"  - model_name: {_alias_repr(alias)}"]
    if responses_mode:
        lines += ["    model_info:", "      mode: responses"]
    lines += [
        "    litellm_params:",
        f"      model: {_yaml_quote(target)}",
    ]
    if provider.needs_api_key:
        lines.append(f"      api_key: {_yaml_quote('os.environ/' + PROVIDER_KEY_ENV)}")
    if api_base or provider.requires_api_base:
        lines.append(f"      api_base: {_yaml_quote('os.environ/' + PROVIDER_BASE_ENV)}")
    return lines


def generate_config(selection: Selection) -> str:
    """Return the full text of a LiteLLM config.yaml for `selection`."""
    provider = selection.provider
    api_base = selection.api_base

    main_responses = needs_responses_api(provider.id, selection.main_model)
    small_responses = needs_responses_api(provider.id, selection.effective_small_model)

    lines: list[str] = [
        "# Generated by ClaudIA - do not edit by hand; it is regenerated each launch.",
        "# Secrets are NOT stored here; they are read from environment variables.",
        f"# provider: {provider.id} ({provider.display_name})",
        "",
        "model_list:",
        "  # Main model - what ANTHROPIC_MODEL points Claude Code at.",
    ]
    lines += _model_entry(MAIN_ALIAS, selection.main_target, provider, api_base, main_responses)
    lines.append("")
    lines.append("  # Small/fast model - Claude Code's background tasks (titles, git, etc.).")
    lines += _model_entry(SMALL_ALIAS, selection.small_target, provider, api_base, small_responses)

    if selection.catch_all:
        lines.append("")
        lines.append("  # Catch-all: any tier Claude Code requests but we didn't map -> main.")
        # The catch-all maps to main, so it inherits main's endpoint mode.
        lines += _model_entry("*", selection.main_target, provider, api_base, main_responses)

    lines += [
        "",
        "litellm_settings:",
        "  drop_params: true          # silently drop Anthropic params the target can't take",
        "  num_retries: 2",
        "",
        "general_settings:",
        f"  master_key: {_yaml_quote('os.environ/' + MASTER_KEY_ENV)}",
        "",
    ]
    return "\n".join(lines)


def write_config(selection: Selection, path: Path) -> Path:
    """Write the generated config to `path`, creating parent dirs. Returns path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_config(selection), encoding="utf-8")
    return path
